/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv src/worker-configuration.d.ts` (hash: 3fbfe24ad689edd310fb8fd9803e4f5c)
interface __BaseEnv_CloudflareEnv {
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	CORS_ORIGIN: string;
	EGRESS_REPLAY_GUARD: DurableObjectNamespace<import("./worker").EgressReplayGuard>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "EgressReplayGuard";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_ANON_KEY" | "CORS_ORIGIN">> {}
}
